### ISSUE TITLE
1.1.6_NEW_RELEASE not reproducible

### ISSUE THREAD

**Issue by IzzySoft** [JustDeax/ComposeStopwatch#1]
and the dex diff is huge. Did you really build that APK from the commit the tag points to? The embedded `version-control-info.textproto` says so, but it is hard to believe. Was the tree clean? No local modifications, no cached artifacts? Diff from your APK against the one I built from the tag:

```diff
  -rw-r--r--  0.0 unx      120 b-      117 defN 1981-01-01 01:01:02 2633a4aa META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     3581 b-     3581 stor 1981-01-01 01:01:02 6fa6547d assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     3581 b-     3581 stor 1981-01-01 01:01:02 338978ae assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      419 b-      419 stor 1981-01-01 01:01:02 e51e722f assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  1945768 b-   934115 defN 1981-01-01 01:01:02 13acc5a0 classes.dex
+ -rw-r--r--  0.0 unx  1944912 b-   933788 defN 1981-01-01 01:01:02 abbfc1b6 classes.dex
  -rw-r--r--  0.0 unx     7112 b-     7112 stor 1981-01-01 01:01:02 4f56ac38 lib/arm64-v8a/libdatastore_shared_counter.so
```

Diff of the `classes.dex`: [dex.diff.gz](https://github.com/user-attachments/files/17003452/dex.diff.gz)

cc @obfusk

**Comment by JustDeax** [comment]
Yes, I did build it from the last commit, I don't know how to prove it, but there is an update coming out soon anyway, hopefully it will be correct? @IzzySoft

**Comment by JustDeax** [comment]
No local modifications, no cached artifacts were present

**Comment by JustDeax** [comment]
Can I close this problem? I will update the app soon, if this problem happens again we can open it again probably

**Comment by IzzySoft** [comment]
Apologies for the late response, I was on vacation the last 3 weeks.As v1.7.2 built fine and RB, the issue can indeed be considered solved, thanks!
